apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: flowcore
  description: Main Image for Navigator Apps - A Python-based application framework for building scalable applications
  annotations:
    github.com/project-slug: Trocdigital/flowcore
    backstage.io/techdocs-ref: dir:.
spec:
  dependsOn:
   - resource:default/argocd
  type: service
  lifecycle: dev
  owner: navigator_platforms
  system: navigator-system
  tags:
    - python
    - api
    - navigator
    - docker
