version: '3.3'

networks:
  navigator:
    name: navigator

services:

  navapi:
    container_name: navtest
    image: python:3.10.13-slim-bookworm
    restart: 'no'
    build: ./navapi
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - /home/jesuslara/proyectos/navigator/navapi:/code
    command: /bin/bash -c "make image && python /code/run.py"
    environment:
      SITE_ROOT: /code
    networks:
      - navigator
    ports:
      - 5000:5000
    extra_hosts:
      - nav-api.dev.local:192.168.1.25
      - navigator-dev.dev.local:192.168.1.25
      - rethink.dev.local:192.168.1.25
      - postgres.dev.local:192.168.1.25
      - api.dev.local:192.168.1.25
