install:
	pip install wheel==0.42.0
	pip install --upgrade asyncdb[all]
	pip install --upgrade navconfig[all]
	pip install --upgrade navigator-api[locale]
	pip install --upgrade navigator-session
	pip install --upgrade navigator-auth
	pip install --upgrade async-notify[all]
	# Install extra resources
	pip install --upgrade aiosftp
	pip install --upgrade qworker
	# QS
	pip install --upgrade querysource
	# install DataIntegrator
	pip install --upgrade flowtask
