install:
	pip install --upgrade python-datamodel
	pip install --upgrade asyncdb[all]
	pip install --upgrade navconfig[all]
	pip install --upgrade async-notify[all]
	pip install --upgrade navigator-api[locale,uvloop]
	# Navapi requirements:
	pip install polyline==2.0.1
	pip install cartopy==0.22.0
	pip install transitions==0.9.0
	pip install aioboto3
	# Nav requirements:
	pip install --upgrade navigator-session
	pip install --upgrade navigator-auth
	pip install --upgrade querysource
